firstname_field_loc = "#firstname"
lastname_field_loc = "#lastname"
email_field_loc = "#email_address"
password_field_loc = "#password"
confirm_password_field_loc = "#password-confirmation"
btn_create_account_loc = "//button[@title='Create an Account']"
success_message_loc = "//div[@data-ui-id='message-success']"
error_required_field_message_loc = "//div[text()='This is a required field.']"
password_confirmation_error_loc = "//div[text()='Please enter the same value again.']"
